# Generated by Django 2.1.4 on 2019-01-23 05:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('comment', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('expected', 'expected'), ('check-in', 'check-in'), ('check-out', 'check-out')], max_length=128)),
                ('date', models.DateField(default=datetime.date.today)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('host', models.ManyToManyField(related_name='relateds', to='app.Host')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Map')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('licenseplate', models.CharField(max_length=20)),
                ('about', models.CharField(max_length=50, null=True)),
                ('comment', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relateds', to='app.Visitor'),
        ),
    ]
