# Generated by Django 2.1.4 on 2019-01-06 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('comment', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('expected', 'expected'), ('check-in', 'check-in'), ('check-out', 'check-out')], max_length=128)),
                ('company_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('licenseplate', models.IntegerField(null=True)),
                ('about', models.CharField(max_length=50, null=True)),
                ('comment', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('visiting', models.ManyToManyField(related_name='relateds', to='app.Host')),
            ],
        ),
    ]
