# Generated by Django 2.1.7 on 2019-03-06 10:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='user',
        ),
        migrations.AddField(
            model_name='meeting',
            name='counter',
            field=models.CharField(choices=[('by-kiosk', 'by-kiosk'), ('by-dashboard', 'by-dashboard'), ('not-check-in', 'not-check-in')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='meeting',
            name='our_company',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TheCompany'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='pre_registred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitor',
            name='our_company',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TheCompany'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2019, 3, 6, 11, 7, 16, 139442, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('expected', 'expected'), ('check-in', 'check-in'), ('check-out', 'check-out')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
    ]
