# Generated by Django 2.1.7 on 2019-03-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190306_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='pre_registred',
        ),
        migrations.AddField(
            model_name='meeting',
            name='pre_registered',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
