# Generated by Django 2.1.7 on 2019-03-04 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190304_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='user',
        ),
        migrations.AddField(
            model_name='meeting',
            name='our_company',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TheCompany'),
        ),
    ]
