# Generated by Django 2.1.4 on 2019-02-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190205_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='media_data/profile-placeholder.png', upload_to='media_data'),
        ),
    ]
