# Generated by Django 2.1.4 on 2019-02-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190205_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='profile_pic',
            field=models.ImageField(default='media_data/profile-pic.png', upload_to='media_data'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='media_data/profile-pic.png', upload_to='media_data'),
        ),
    ]
