# Generated by Django 2.1.7 on 2019-03-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_meeting_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('1', 'student'), ('2', 'teacher'), ('3', 'secretary'), ('4', 'supervisor'), ('5', 'admin')], default='', max_length=20),
        ),
    ]
