# Generated by Django 2.1.7 on 2019-03-13 07:11

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190313_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deliverytype', models.CharField(max_length=30)),
                ('which_date', models.DateField(default=django.utils.timezone.now)),
                ('which_time', models.TimeField()),
                ('which_user', models.ManyToManyField(default='', related_name='related_userdelivery', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
