# Generated by Django 2.1.7 on 2019-03-13 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='our_company',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TheCompany'),
        ),
    ]
