# Generated by Django 2.1.7 on 2019-03-14 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delivery_our_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='counter',
            field=models.CharField(choices=[('by-kiosk', 'by-kiosk'), ('by-dashboard', 'by-dashboard'), ('not-check-in', 'not-check-in')], default='by-dashboard', max_length=15),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='visitor',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_visitor', to='app.Visitor'),
        ),
    ]
