# Generated by Django 2.1.7 on 2019-03-15 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190314_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='colleague',
        ),
    ]
